from django.urls import path
from . import views
from .views import toggle_induction_status, internship_stats_view, AttendedInternsView, CreateCompanyLogbookPreview, DistributeLogbookToInterns, EventsView, InternLogbookView, QualificationsView,TemplateView, RegisterHostCompanySuccessView, UpdateApprovalStatus, create_event, get_event_by_date, get_events, manage_leave_requests, update_event, work_attendance_list, admit_all_applications, RegisterHostCompanyView, update_passcode, export_applications_view,import_applications
from .views import (
    HomeView,
    InductionApplicationsView,
    CreateInductionPostView,
    InductionPostSuccessCreateView,
    ViewInductionPostApplications,
    ViewInductionApplicantView,
    ViewQuestionnaireView,
    InductionAttendanceView,
    HostEmployerView,
    InternProfileView,
    RegisterHostEmployerView,
    HostEmployersListView,
    NewsLettersView,
    Host,
    AllInternsView,
    ExitReport,
    AssesmentListView,
    ViewAssignment,
    HearingCreateView,
    QualificationView, 
    WorkItemView,
    AssesmentTwoListView,
    ViewAssignmentTwo,
    AssesmentListAllView,
    InductionAssigmentsView,
    InductionAssigmentsTwoView,
    UploadProfilePictureView,
    UploadCvView,
    UploadQualificationView,
    BulkAssignWorkItemsView,
    AddSubjectView,
    ViewAllApplications,
    HRDashboardView
)

urlpatterns = [
    path("", view=HomeView.as_view(), name="admini-home"),
    path('hr-stats/', view=HRDashboardView.as_view(), name='hr_dashboard_stats'),
    path("induction", view=InductionApplicationsView.as_view(), name="induction"),
    path("induction/<int:post_id>/assesment", view=AssesmentListView.as_view(), name="assesment"),
    path(
        "induction/assesment/<int:id>",
        view=ViewAssignment.as_view(),
        name="assesment",
    ),
    path("induction/<int:post_id>/assesment2", view=AssesmentTwoListView.as_view(), name="assesment2"),
    path("assesments", AssesmentListAllView.as_view(), name="assesments"),
    path(
        "induction/assesment2/<int:id>",
        view=ViewAssignmentTwo.as_view(),
        name="assesment2",
    ),
    path(
        "induction/application/<int:id>",
        view=ViewInductionPostApplications.as_view(),
        name="induction-application-posts",
    ),
    path(
        "induction/application",
        view=ViewAllApplications.as_view(),
        name="all-application",
    ),
    path('admit-all/', admit_all_applications, name='admit-all-applications'),
    path(
        "induction/application/view/<int:id>",
        view=ViewInductionApplicantView.as_view(),
        name="induction-application-view",
    ),
    path(
        "induction-attendance-view",
        view=InductionAttendanceView.as_view(),
        name="induction-attendance-view",
    ),
    path(
        "induction-assingment-one-view",
        view=InductionAssigmentsView.as_view(),
        name="induction-assigment-one-view",
    ),
    path(
        "induction-assingment-two-view",
        view=InductionAssigmentsTwoView.as_view(),
        name="induction-assigment-two-view",
    ),
    path('import-applications/', import_applications, name='import_applications'),
    path('export-applications/', export_applications_view, name='export_applications'),
    path(
        "induction/create",
        view=CreateInductionPostView.as_view(),
        name="induction-create",
    ),
    path(
        "induction/create/success",
        view=InductionPostSuccessCreateView.as_view(),
        name="induction-create-success",
    ),
    path(
        "questionnaire/view/<int:id>/",
        ViewQuestionnaireView.as_view(),
        name="view_questionnaire",
    ),
    path(
        "induction/<int:post_id>/attended_interns/",
        AttendedInternsView.as_view(),
        name="view_attended_interns",
    ),
    path(
        "induction/<int:post_id>/update_passcode/",
        update_passcode,
        name="update_passcode",
    ),
    path(
        "hostemployer/<int:pk>/", HostEmployerView.as_view(), name="edit_hostemployer"
    ),
    path(
        "intern_profil/<int:intern_id>/",
        InternProfileView.as_view(),
        name="intern_profil",
    ),
    path(
    "intern_profil/upload-contract/<int:enrollment_id>/",
    views.upload_contract,
    name="upload_contract",
    ),

    path("waiting/", views.waiting_internships, name="waiting_internships"),
    path("host/", view=Host.as_view(), name="Host"),
    path("hearings/create/", HearingCreateView.as_view(), name="hearing_create"),
    path("placed/", views.placed_internships, name="placed_internships"),
    path("terminated/", views.terminated_internships, name="terminated_internships"),
    path("defaulted/", views.defaulted_internships, name="defaulted_internships"),
    path("completed/", views.completed_internships, name="completed_internships"),
    path("host-employers/", HostEmployersListView.as_view(), name="host_employer_list"),
    path('intern_profile/<int:enrollment_id>/upload-picture/', UploadProfilePictureView.as_view(), name='upload_profile_picture'),
    path('intern_profile/<int:application_id>/upload-cv/', UploadCvView.as_view(), name='upload_cv'),
    path('intern_profile/<int:application_id>/upload-qualification/', UploadQualificationView.as_view(), name='upload_qualification'),

    path(
        "register-host-employer/",
        RegisterHostEmployerView.as_view(),
        name="register_host_employer",
    ),
    path("register-host-company/<int:pk>/", RegisterHostCompanyView.as_view(), name="register_host_company"),
    path("register-host-company/success/", RegisterHostCompanySuccessView.as_view(), name="register_host_company-success"),
    path(
        "place_intern/<int:enrollment_id>/<int:intern_id>/",
        views.place_intern,
        name="place_intern",
    ),
    path(
        "terminate_internship/<int:intern_id>/",
        views.terminate_intern,
        name="terminate_internship",
    ),
    path(
        "default_intern/<int:intern_id>/",
        views.default_intern,
        name="default_intern",
    ),
    path("complet_intern/<int:intern_id>/",
        views.complet_intern,
        name="complet_intern",),
    path(
        "bypass-induction/<int:application_id>/",
        views.intern_bypass_induction,
        name="bypass-induction",
    ),
    path("posts/news", NewsLettersView.as_view(), name="news_letters"),
    path("interns/all", ExitReport.as_view(), name="exitreport"),
    path("exitreport", AllInternsView.as_view(), name="all-interns"),
    path("work-attendance-list/", views.work_attendance_list, name="work_attendance_list"),
    path("meet-attendance-list/", views.meeting_attendance_list, name="meeting_attendance_list"),
    path('admin/generate-attendance-pdf/', views.generate_attendance_pdf, name='generate_attendance_pdf'),
    path('manage-leave-requests/', manage_leave_requests, name='manage_leave_requests'),
    path("event-management", EventsView.as_view(), name="event-management"),
    path("induction/toggle-status/<int:induction_id>/", toggle_induction_status, name="toggle-induction-status"),
    path('events/', EventsView.as_view(), name='events'),
    path('events/data/', get_events, name='events-data'),
    path('stats/', internship_stats_view, name='company-stats'),
    path('events/create/', create_event, name='create-event'),
    path('events/data/view', get_event_by_date, name='create-event'),
    path('events/<int:event_id>/update/', update_event, name='update-event'),
    path('events-by-date/', views.events_by_date, name='events_by_date'),
    # Logbook Management
    path('qualifications/', QualificationsView.as_view(), name='qualifications'),
    path('qualification/<int:qualification_id>', QualificationView.as_view(), name='qualification'),
    path('qualification/workitem/<int:workitem_id>', WorkItemView.as_view(), name='workitem'), 
    path(
        "companies/logbook/<int:logbook_template_id>/",
        CreateCompanyLogbookPreview.as_view(),
        name="company-preview-logbook",
    ),
    path(
        "companies/logbook/<int:logbook_template_id>/assignment/<int:company_id>/",
        DistributeLogbookToInterns.as_view(),
        name="distribute-logbook",
    ),
    path('logbook/intern/<int:intern_id>', InternLogbookView.as_view(), name='admin_intern_logbook'),
    path('logbook/approval-status', UpdateApprovalStatus.as_view(), name='approval-status'),
    path('workitems/bulk-assign/', BulkAssignWorkItemsView.as_view(), name='bulk-assign'),
    path("subjects/add/", AddSubjectView.as_view(), name="add_subject"),
    path("close-popup/", TemplateView.as_view(template_name="administration/pages/qualifications/close_popup.html"), name="close_popup"),

    path("invoices/", views.CompanyInvoiceListView.as_view(), name="company_invoice_list"),
    path("invoices/<int:company_id>/", views.MonthlyInvoiceListView.as_view(), name="monthly_invoice_list"),
    path("invoices/detail/<int:pk>/", views.InvoiceDetailView.as_view(), name="invoice_detail"),
    path("invoices/generate/", views.generate_invoices, name="generate_invoices"),

    path('financial-dashboard/', views.FinancialDashboardView.as_view(), name='financial_dashboard'),
    path('induction-dashboard/', views.InductionDashboardView.as_view(), name='induction_dashboard'),
    path('questionnaire-dashboard/', views.QuestionnaireDashboardView.as_view(), name='questionnaire_dashboard'),
    
    path('payment_list/', views.PaymentListView.as_view(), name='payment_list'),
    path('add/', views.PaymentCreateView.as_view(), name='payment_add'),
    path('<int:pk>/edit/', views.PaymentUpdateView.as_view(), name='payment_edit'),
    path('<int:pk>/delete/', views.PaymentDeleteView.as_view(), name='payment_delete'),


    path('reset_interns/', views.reset_all_interns_to_waiting, name='reset_interns_to_waiting'),
]
