# Generated by Django 5.1.1 on 2025-03-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Magazine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("issue_date", models.DateField()),
                ("pdf", models.FileField(upload_to="magazines/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
