# Generated by Django 5.1.1 on 2025-03-18 09:58

import marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0002_magazine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazine",
            name="pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=marketing.models.magazine_pdf_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="successstory",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=marketing.models.successstory_directory_path,
            ),
        ),
    ]
