# Generated by Django 5.1.1 on 2025-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0003_alter_magazine_pdf_alter_successstory_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_person", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("form_date", models.DateField()),
                ("purpose_training", models.BooleanField(default=False)),
                ("purpose_marketing", models.BooleanField(default=False)),
                ("purpose_awareness", models.BooleanField(default=False)),
                ("purpose_commercial", models.BooleanField(default=False)),
                ("content_photos", models.BooleanField(default=False)),
                ("content_videos", models.BooleanField(default=False)),
                ("content_audio", models.BooleanField(default=False)),
                ("content_testimonials", models.BooleanField(default=False)),
                ("content_story", models.BooleanField(default=False)),
                ("full_name", models.CharField(max_length=255)),
                ("id_number", models.CharField(max_length=20)),
                ("dob", models.DateField()),
                ("age", models.PositiveIntegerField()),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("role_intern", models.BooleanField(default=False)),
                ("role_employer", models.BooleanField(default=False)),
                ("role_employee", models.BooleanField(default=False)),
                ("role_public", models.BooleanField(default=False)),
                ("role_ambassador", models.BooleanField(default=False)),
                ("role_influencer", models.BooleanField(default=False)),
                (
                    "consent",
                    models.CharField(
                        choices=[("yes", "I consent"), ("no", "I do NOT consent")],
                        max_length=10,
                    ),
                ),
                (
                    "signature_data",
                    models.TextField(help_text="Base64-encoded image of the signature"),
                ),
                ("sign_date", models.DateField()),
                ("is_minor", models.BooleanField(default=False)),
                ("minor_name", models.CharField(blank=True, max_length=255, null=True)),
                ("minor_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "guardian_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "guardian_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "guardian_consent",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "I consent"), ("no", "I do NOT consent")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "guardian_signature_data",
                    models.TextField(
                        blank=True,
                        help_text="Base64-encoded image of the guardian's signature",
                        null=True,
                    ),
                ),
                ("guardian_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
