# Generated by Django 5.1.1 on 2025-06-07 23:18

import marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0004_consentform"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazine",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=marketing.models.magazine_cover_image_path,
            ),
        ),
    ]
