# Generated by Django 5.1.1 on 2025-06-08 23:21

import marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0005_magazine_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=marketing.models.campaign_directory_path,
            ),
        ),
    ]
