# Generated by Django 5.1.1 on 2025-05-20 14:29

import django.core.validators
import django.db.models.deletion
import hr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="staff_photos/"),
                ),
                ("date_joined", models.DateField(auto_now_add=True)),
                (
                    "rsa_id_number",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 13-digit RSA ID number.",
                                regex="^\\d{13}$",
                            )
                        ],
                    ),
                ),
                (
                    "id_document",
                    models.FileField(
                        blank=True, null=True, upload_to=hr.models.id_doc_directory_path
                    ),
                ),
                (
                    "drivers_license",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=hr.models.drivers_license_directory_path,
                    ),
                ),
                (
                    "contract_agreement",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=hr.models.contract_doc_directory_path,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_members",
                        to="hr.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
