# Generated by Django 5.1.1 on 2025-05-20 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_department_staff"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StaffProfile",
        ),
    ]
