# Generated by Django 5.1.1 on 2025-05-20 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0003_delete_staffprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="role",
        ),
    ]
