# Generated by Django 5.1.1 on 2025-05-22 14:25

import django.db.models.deletion
import hr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0004_remove_staff_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("PETROL", "Petrol"),
                            ("DIESEL", "Diesel"),
                            ("ELECTRIC", "Electric"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FREE", "Free for Use"),
                            ("BUSY", "In Use"),
                            ("DAMAGED", "Damaged"),
                            ("MAINTENANCE", "In Maintenance"),
                        ],
                        default="FREE",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
                ("destination", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hr.vehicle"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_odometer", models.PositiveIntegerField()),
                (
                    "open_odometer_proof",
                    models.ImageField(upload_to=hr.models.vehicle_proof_upload_path),
                ),
                ("close_odometer", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "close_odometer_proof",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=hr.models.vehicle_proof_upload_path,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.vehiclerequest",
                    ),
                ),
            ],
        ),
    ]
