# Generated by Django 5.1.1 on 2025-05-22 14:37

import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0005_vehicle_vehiclerequest_vehicleusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=hr.models.vehicle_proof_upload_path
            ),
        ),
    ]
