# Generated by Django 5.1.1 on 2025-05-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0006_vehicle_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclerequest",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hr.staff"
            ),
        ),
    ]
