# Generated by Django 5.1.1 on 2025-05-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0007_alter_vehiclerequest_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclerequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
