# Generated by Django 5.1.1 on 2025-05-29 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0008_vehiclerequest_approved_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ScoringTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="hr.scoringcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffScoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appraisal_date", models.DateField(auto_now_add=True)),
                ("total_points", models.PositiveIntegerField(default=0)),
                (
                    "percentage_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "performance_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Superior"),
                            ("B", "Excellent"),
                            ("C", "Average"),
                            ("D", "Below Average"),
                            ("F", "Poor"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_sessions",
                        to="hr.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffTaskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (4, "Fully Achieved"),
                            (3, "To a Greater Degree"),
                            (2, "To an Accepted Degree"),
                            (1, "To a Lesser Degree"),
                            (0, "Not at All"),
                        ]
                    ),
                ),
                (
                    "scoring_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_scores",
                        to="hr.staffscoring",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hr.scoringtask"
                    ),
                ),
            ],
        ),
    ]
