# Generated by Django 5.1.1 on 2025-05-29 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0009_scoringcategory_scoringtask_staffscoring_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringcategory",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="hr.department",
            ),
            preserve_default=False,
        ),
    ]
