# Generated by Django 5.2.5 on 2025-09-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0010_scoringcategory_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
