# Generated by Django 4.0.8 on 2024-05-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostComapany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(help_text='Explain what the company do.')),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=10000, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_comapanies', to='authentication.hostemployer')),
            ],
        ),
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('months', models.IntegerField(default=18)),
                ('total_credits', models.IntegerField(default=180)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_logbooks', to='hostCampany.hostcomapany')),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostCampany.logbook')),
            ],
        ),
        migrations.CreateModel(
            name='LogBookAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbooks_interns', to='authentication.intern')),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_assignments', to='hostCampany.logbook')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_departments', to='hostCampany.hostcomapany')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decription', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_deliverables', to='hostCampany.workitem')),
            ],
        ),
    ]
