# Generated by Django 4.0.8 on 2024-05-22 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostCampany', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcomapany',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_comapanies', to=settings.AUTH_USER_MODEL),
        ),
    ]
