# Generated by Django 5.0.2 on 2024-05-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostCampany', '0003_alter_hostcomapany_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='logbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_workitems', to='hostCampany.logbook'),
        ),
    ]
