# Generated by Django 4.0.8 on 2024-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostCampany', '0005_alter_hostcomapany_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostcomapany',
            name='passcode',
            field=models.CharField(blank=True, default='internship#@', max_length=50, null=True),
        ),
    ]
