# Generated by Django 5.1.1 on 2024-11-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostCampany", "0010_rename_timestamp_report_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("resolved", "Resolved")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
