# Generated by Django 5.0.2 on 2024-11-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostCampany', '0011_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='company',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='intern',
        ),
        migrations.RemoveField(
            model_name='logbookassignment',
            name='logbook',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='logbook',
        ),
        migrations.RemoveField(
            model_name='logbookassignment',
            name='intern',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='intern',
        ),
        migrations.DeleteModel(
            name='Deliverables',
        ),
        migrations.DeleteModel(
            name='LogBook',
        ),
        migrations.DeleteModel(
            name='LogBookAssignment',
        ),
        migrations.DeleteModel(
            name='WorkItem',
        ),
    ]
