# Generated by Django 5.1.1 on 2025-06-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0056_alter_intershipenrollment_status"),
        ("hostCampany", "0013_rotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rotation",
            name="intern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rotations",
                to="administration.intershipenrollment",
            ),
        ),
    ]
