# Generated by Django 5.1.1 on 2025-07-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0056_alter_intershipenrollment_status"),
        ("hostCampany", "0015_interninvoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interninvoice",
            name="due_date",
        ),
        migrations.AddField(
            model_name="interninvoice",
            name="expected_day_of_month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1th"),
                    (2, "2th"),
                    (3, "3th"),
                    (4, "4th"),
                    (5, "5th"),
                    (6, "6th"),
                    (7, "7th"),
                    (8, "8th"),
                    (9, "9th"),
                    (10, "10th"),
                    (11, "11th"),
                    (12, "12th"),
                    (13, "13th"),
                    (14, "14th"),
                    (15, "15th"),
                    (16, "16th"),
                    (17, "17th"),
                    (18, "18th"),
                    (19, "19th"),
                    (20, "20th"),
                    (21, "21th"),
                    (22, "22th"),
                    (23, "23th"),
                    (24, "24th"),
                    (25, "25th"),
                    (26, "26th"),
                    (27, "27th"),
                    (28, "28th"),
                    (29, "29th"),
                    (30, "30th"),
                    (31, "31th"),
                ],
                default="1",
                help_text="Select the day of the month when payment is expected (e.g., 1 = 1st of every month)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="interninvoice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The total amount to be charged monthly for the intern",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="interninvoice",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="interninvoice",
            name="enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.intershipenrollment",
            ),
        ),
        migrations.AlterField(
            model_name="interninvoice",
            name="host_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="hostCampany.hostcomapany",
            ),
        ),
    ]
