# Generated by Django 5.1.1 on 2025-07-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostCampany", "0016_remove_interninvoice_due_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyCompanyInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(help_text="First day of the invoice month")),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "approval",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("APPROVED", "Approved")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_invoices",
                        to="hostCampany.hostcomapany",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "month")},
            },
        ),
    ]
