# Generated by Django 4.0.8 on 2024-06-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_application_applicant'),
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workattendance',
            unique_together={('intern', 'date')},
        ),
        migrations.RemoveField(
            model_name='workattendance',
            name='shift',
        ),
    ]
