# Generated by Django 4.0.8 on 2024-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_alter_workattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workattendance',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
