# Generated by Django 5.0.2 on 2024-06-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_alter_workattendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
