# Generated by Django 4.0.8 on 2024-06-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_attendance_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='workattendance',
            name='sign_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workattendance',
            name='sign_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workattendance',
            name='date',
            field=models.DateField(),
        ),
    ]
