# Generated by Django 5.1.1 on 2024-10-04 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intern", "0007_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="assesment",
        ),
        migrations.RemoveField(
            model_name="question",
            name="assesment",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="question",
        ),
        migrations.RemoveField(
            model_name="response",
            name="user",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Assesment",
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Response",
        ),
    ]
