# Generated by Django 5.1.1 on 2024-10-04 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intern", "0008_remove_response_assesment_remove_question_assesment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_1", models.TextField()),
                ("question_2_personal", models.TextField()),
                ("question_2_professional", models.TextField()),
                ("question_3", models.TextField()),
                ("question_4_personal", models.TextField()),
                ("question_4_professional", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
