# Generated by Django 5.1.1 on 2024-10-04 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("intern", "0009_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="intern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.intern"
            ),
        ),
    ]
