# Generated by Django 5.1.1 on 2024-10-04 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intern", "0011_alter_assignment_intern"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="question_1",
            new_name="answer",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="question_2_personal",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="question_2_professional",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="question_3",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="question_4_personal",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="question_4_professional",
        ),
    ]
