# Generated by Django 5.1.1 on 2024-10-08 07:40

import intern.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intern", "0012_rename_question_1_assignment_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="answer",
            field=models.FileField(
                blank=True, null=True, upload_to=intern.models.assignment_directory_path
            ),
        ),
    ]
