# Generated by Django 5.1.1 on 2024-12-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intern", "0013_alter_assignment_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="workattendance",
            name="type",
            field=models.CharField(
                choices=[("WORK", "Work"), ("MEETING", "Meeting")],
                default="UNAVAILABLE",
                max_length=50,
            ),
        ),
    ]
