# Generated by Django 5.1.1 on 2025-03-31 13:07

import intern.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intern", "0015_assignmenttwo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="answer",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=intern.models.assignment_two_directory_path,
            ),
        ),
    ]
