# Generated by Django 5.1.1 on 2025-04-01 12:53

import intern.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intern", "0016_alter_assignment_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="answer",
            field=models.FileField(
                blank=True, null=True, upload_to=intern.models.assignment_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="assignmenttwo",
            name="answer",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=intern.models.assignment_two_directory_path,
            ),
        ),
    ]
