# Generated by Django 5.1.1 on 2025-04-01 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0051_questionnaire_first_assignment_and_more"),
        ("intern", "0017_alter_assignment_answer_alter_assignmenttwo_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="induction_post",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigment_answer",
                to="administration.inductionpost",
            ),
        ),
        migrations.AddField(
            model_name="assignmenttwo",
            name="induction_post",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigment_answer2",
                to="administration.inductionpost",
            ),
        ),
    ]
