# Generated by Django 4.0.8 on 2024-05-22 09:57

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('resume_cv', models.FileField(blank=True, null=True, upload_to=administration.models.cv_directory_path)),
                ('qualification_document', models.FileField(blank=True, null=True, upload_to=administration.models.qualification_directory_path)),
                ('college_name', models.CharField(default='None', max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=50, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification_description', models.TextField(blank=True, null=True)),
                ('residental_address', models.CharField(blank=True, max_length=255, null=True)),
                ('post_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('ADMITTED', 'Admitted'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ACKNOWLEDGED', 'Acknowledged')], default='PENDING', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InductionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('day_1', models.BooleanField(default=False)),
                ('day_2', models.BooleanField(default=False)),
                ('pending_placement', models.BooleanField(default=False)),
                ('placed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InductionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(help_text='Explain what the application post is about.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('passcode', models.CharField(blank=True, default='internship#@', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntershipEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('WAITING', 'Waiting'), ('PLACED', 'Placed'), ('TERMINATED', 'Terminated'), ('COMPLETED', 'Completed')], default='WAITING', max_length=50, null=True)),
                ('contract', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_info', models.TextField(blank=True)),
                ('dream_personal', models.TextField(blank=True)),
                ('dream_professional', models.TextField(blank=True)),
                ('plan_personal', models.TextField(blank=True)),
                ('plan_professional', models.TextField(blank=True)),
                ('internship_success_before', models.BooleanField(default=False)),
                ('internship_before', models.BooleanField(default=False)),
                ('pregnant', models.BooleanField(default=False)),
                ('pregnancy_weeks', models.IntegerField(blank=True, null=True)),
                ('pregnancy_months', models.IntegerField(blank=True, null=True)),
                ('criminal_record', models.BooleanField(default=False)),
                ('qualification_completed', models.BooleanField(default=False)),
                ('qualification_completion_date', models.DateField(blank=True, null=True)),
                ('stipend_eligibility', models.BooleanField(default=False)),
                ('willing_to_relocate_nelspruit', models.BooleanField(default=False)),
                ('willing_to_relocate_barberton', models.BooleanField(default=False)),
                ('willing_to_work_shifts', models.BooleanField(default=False)),
                ('acceptance_statement', models.BooleanField(default=False)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('signature_place', models.CharField(blank=True, max_length=255)),
                ('witness_name', models.CharField(blank=True, max_length=255)),
                ('witness_signature', models.CharField(blank=True, max_length=255)),
                ('affidavit', models.FileField(blank=True, null=True, upload_to='affidavits/')),
            ],
        ),
        migrations.CreateModel(
            name='RecordAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('placing', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
