# Generated by Django 4.0.8 on 2024-05-22 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostCampany', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='hostCampany.hostcomapany'),
        ),
        migrations.AddField(
            model_name='recordaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hcompany', to='authentication.hostemployer'),
        ),
        migrations.AddField(
            model_name='recordaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RAuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='administration.application'),
        ),
        migrations.AddField(
            model_name='intershipenrollment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internCompany', to='hostCampany.hostcomapany'),
        ),
        migrations.AddField(
            model_name='intershipenrollment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostCampany.department'),
        ),
        migrations.AddField(
            model_name='intershipenrollment',
            name='intern',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_profile', to='authentication.intern'),
        ),
        migrations.AddField(
            model_name='intershipenrollment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift', to='administration.shift'),
        ),
        migrations.AddField(
            model_name='inductionpost',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inductionenrollment',
            name='induction_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='induction_post_enrollments', to='administration.inductionpost'),
        ),
        migrations.AddField(
            model_name='inductionenrollment',
            name='intern_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_enrollments', to='authentication.intern'),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='induction_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='induction_post_applications', to='administration.inductionpost'),
        ),
    ]
