# Generated by Django 4.0.8 on 2024-06-06 11:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_application_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='intershipenrollment',
            name='stipend',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
