# Generated by Django 4.0.8 on 2024-06-10 11:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_intershipenrollment_stipend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intershipenrollment',
            name='stipend',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
