# Generated by Django 4.0.8 on 2024-06-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostCampany', '0008_deliverables_intern_workitem_intern_and_more'),
        ('administration', '0005_alter_intershipenrollment_stipend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hcompany', to='hostCampany.hostcomapany'),
        ),
    ]
