# Generated by Django 5.0.6 on 2024-07-08 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0006_alter_recordaction_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionnaire",
            old_name="background_info",
            new_name="answer",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="dream_personal",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="dream_professional",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="plan_personal",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="plan_professional",
        ),
    ]
