# Generated by Django 5.0.6 on 2024-07-08 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0007_rename_background_info_questionnaire_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
