# Generated by Django 5.0.6 on 2024-07-08 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0008_application_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
