# Generated by Django 5.0.2 on 2024-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_application_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionpost',
            name='closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='inductionpost',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inductionpost',
            name='passcode',
            field=models.CharField(blank=True, default='123456', max_length=50, null=True),
        ),
    ]
