# Generated by Django 5.0.2 on 2024-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_inductionpost_closed_inductionpost_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='national_id',
            field=models.CharField(max_length=255),
        ),
    ]
