# Generated by Django 5.0.2 on 2024-08-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_application_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionenrollment',
            name='bypass_reason',
            field=models.TextField(blank=True, help_text='Explain Explain why this induction was bypassed', null=True),
        ),
        migrations.AddField(
            model_name='inductionenrollment',
            name='bypassed',
            field=models.BooleanField(default=False),
        ),
    ]
