# Generated by Django 5.0.6 on 2024-09-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0013_leaverequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
