# Generated by Django 5.1.1 on 2024-09-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0014_alter_leaverequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="about_me",
            field=models.TextField(blank=True, default="No bio", null=True),
        ),
    ]
