# Generated by Django 5.1.1 on 2024-09-20 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0015_application_about_me"),
        ("administration", "0015_event"),
    ]

    operations = []
