# Generated by Django 5.1.1 on 2024-09-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0016_merge_0015_application_about_me_0015_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("sick", "Sick Leave"),
                    ("Study", "Study"),
                    ("Family", "Family Responsibility"),
                ],
                max_length=20,
            ),
        ),
    ]
