# Generated by Django 5.1.1 on 2024-10-04 12:20

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0017_alter_leaverequest_leave_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMITTED", "Admitted"),
                    ("PENDING", "Pending"),
                    ("NOQUESTIONNAIRE", "NoQuestionnaire"),
                    ("REJECTED", "Rejected"),
                    ("ACKNOWLEDGED", "Acknowledged"),
                ],
                default="PENDING",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="affidavit",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=administration.models.questionnaire_directory_path,
            ),
        ),
    ]
