# Generated by Django 5.1.1 on 2024-10-07 14:08

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0018_alter_application_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaire",
            name="affidavit",
        ),
        migrations.AddField(
            model_name="application",
            name="affidavit",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=administration.models.questionnaire_directory_path,
            ),
        ),
    ]
