# Generated by Django 5.1.1 on 2024-11-18 10:46

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0028_alter_application_affidavit_hearing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hearing",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="application",
            name="affidavit",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=administration.models.questionnaire_directory_path,
            ),
        ),
    ]
