# Generated by Django 5.0.2 on 2024-11-29 04:48

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0030_alter_application_affidavit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=administration.models.questionnaire_directory_path),
        ),
    ]
