# Generated by Django 5.0.2 on 2024-11-30 06:48

import administration.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0031_alter_application_affidavit'),
        ('authentication', '0001_initial'),
        ('hostCampany', '0012_remove_logbook_company_remove_logbook_intern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=administration.models.questionnaire_directory_path),
        ),
        migrations.CreateModel(
            name='LogbookTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_templates', to='hostCampany.hostcomapany')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_templates', to='administration.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='InternLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_logbooks', to='authentication.intern')),
                ('logbooktemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_logbooks_templates', to='administration.logbooktemplate')),
            ],
        ),
        migrations.CreateModel(
            name='LogbookTemplateDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_template_deliverables', to='administration.deliverable')),
                ('logbooktemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='administration.logbooktemplate')),
            ],
        ),
        migrations.CreateModel(
            name='InternDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('intern_logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='administration.internlogbook')),
                ('intern_logbook_deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_logbooks_deliverables', to='administration.logbooktemplatedeliverable')),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workitems', to='administration.qualification')),
            ],
        ),
        migrations.AddField(
            model_name='deliverable',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='administration.workitem'),
        ),
    ]
