# Generated by Django 5.0.2 on 2024-11-30 18:38

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0032_deliverable_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internlogbook',
            name='intern',
        ),
        migrations.RemoveField(
            model_name='internlogbook',
            name='logbooktemplate',
        ),
        migrations.RemoveField(
            model_name='logbooktemplate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='logbooktemplate',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='logbooktemplatedeliverable',
            name='logbooktemplate',
        ),
        migrations.RemoveField(
            model_name='logbooktemplatedeliverable',
            name='deliverable',
        ),
        migrations.AlterField(
            model_name='application',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=administration.models.questionnaire_directory_path),
        ),
        migrations.DeleteModel(
            name='InternDeliverable',
        ),
        migrations.DeleteModel(
            name='InternLogbook',
        ),
        migrations.DeleteModel(
            name='LogbookTemplate',
        ),
        migrations.DeleteModel(
            name='LogbookTemplateDeliverable',
        ),
    ]
