# Generated by Django 5.0.2 on 2024-11-30 18:40

import administration.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0033_remove_internlogbook_intern_and_more'),
        ('hostCampany', '0012_remove_logbook_company_remove_logbook_intern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=administration.models.questionnaire_directory_path),
        ),
        migrations.CreateModel(
            name='LogbookTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_templates', to='hostCampany.hostcomapany')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_templates', to='administration.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='LogbookTemplateDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_template_deliverables', to='administration.deliverable')),
                ('logbook_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='administration.logbooktemplate')),
            ],
        ),
    ]
