# Generated by Django 5.0.2 on 2024-11-30 18:43

import administration.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0034_alter_application_affidavit_logbooktemplate_and_more'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=administration.models.questionnaire_directory_path),
        ),
        migrations.CreateModel(
            name='InternLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to='authentication.intern')),
                ('logbook_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to='administration.logbooktemplate')),
            ],
        ),
        migrations.CreateModel(
            name='InternDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_deliverables', to='administration.logbooktemplatedeliverable')),
                ('intern_logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='administration.internlogbook')),
            ],
        ),
    ]
