# Generated by Django 5.0.2 on 2024-12-02 11:14

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0035_alter_application_affidavit_internlogbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=administration.models.questionnaire_directory_path),
        ),
    ]
