# Generated by Django 5.0.2 on 2024-12-05 08:12

import administration.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0036_alter_application_affidavit'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='duration',
            new_name='duration_in_yrs',
        ),
        migrations.AlterField(
            model_name='application',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=administration.models.questionnaire_directory_path),
        ),
        migrations.AlterField(
            model_name='internlogbook',
            name='intern',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to='authentication.intern'),
        ),
    ]
