# Generated by Django 5.1.1 on 2024-12-09 05:59

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "administration",
            "0037_rename_duration_qualification_duration_in_yrs_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="affidavit",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=administration.models.questionnaire_directory_path,
            ),
        ),
    ]
