# Generated by Django 5.1.1 on 2024-12-09 06:54

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0038_alter_application_affidavit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="affidavit",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=administration.models.questionnaire_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="intershipenrollment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WAITING", "Waiting"),
                    ("PLACED", "Placed"),
                    ("TERMINATED", "Terminated"),
                    ("COMPLETED", "Completed"),
                    ("DEFAULTED", "Defaulted"),
                ],
                default="WAITING",
                max_length=50,
                null=True,
            ),
        ),
    ]
