# Generated by Django 5.0.2 on 2024-12-18 07:17

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0039_alter_application_affidavit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_your_location_far',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='willing_to_work_hospitality_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='willing_to_work_paid_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='willing_to_work_unpaid_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=administration.models.questionnaire_directory_path),
        ),
    ]
