# Generated by Django 5.1.1 on 2025-01-30 08:12

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0040_application_is_your_location_far_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=administration.models.questionnaire_directory_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=administration.models.questionnaire_directory_path),
        ),
    ]
