# Generated by Django 5.1.1 on 2025-03-09 11:44

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0044_alter_application_affidavit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="affidavit",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=administration.models.questionnaire_directory_path,
            ),
        ),
    ]
