# Generated by Django 5.1.1 on 2025-03-18 09:58

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0047_alter_application_affidavit"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="affidavit",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=administration.models.questionnaire_directory_path,
            ),
        ),
    ]
