# Generated by Django 5.0.4 on 2025-03-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0048_application_email_verified_application_otp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('induction_post', 'national_id')},
        ),
        migrations.AlterField(
            model_name='application',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to='questionnaire/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='induction_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='induction_post_applications', to='administration.inductionpost'),
        ),
        migrations.AlterField(
            model_name='application',
            name='qualification_document',
            field=models.FileField(blank=True, null=True, upload_to='qualification/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume_cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.RemoveField(
            model_name='application',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='application',
            name='otp_created_at',
        ),
    ]
