# Generated by Django 5.1.1 on 2025-03-23 21:06

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0049_alter_application_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="sick_note",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=administration.models.sick_note_directory_path,
            ),
        ),
    ]
