# Generated by Django 5.1.1 on 2025-03-27 08:23

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0050_leaverequest_sick_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="first_assignment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=administration.models.first_assigment_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="affidavit",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=administration.models.affidavit_directory_path,
            ),
        ),
    ]
