# Generated by Django 5.1.1 on 2025-04-06 16:51

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0051_questionnaire_first_assignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intershipenrollment",
            name="contrac_doc",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=administration.models.contract_doc_directory_path,
            ),
        ),
    ]
