# Generated by Django 5.1.1 on 2025-04-08 17:31

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0052_intershipenrollment_contrac_doc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intershipenrollment",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=administration.models.profile_pic_directory_path,
            ),
        ),
    ]
