# Generated by Django 5.1.1 on 2025-05-06 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0054_subject_workitem_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="qualification",
        ),
    ]
