# Generated by Django 5.1.1 on 2025-05-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0055_remove_subject_qualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intershipenrollment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WAITING", "Waiting"),
                    ("PLACED", "Placed"),
                    ("TERMINATED", "Terminated"),
                    ("COMPLETED", "Completed"),
                    ("DEFAULTED", "Defaulted"),
                    ("PENDING_LOGBOOK", "pending logbook"),
                ],
                default="WAITING",
                max_length=50,
                null=True,
            ),
        ),
    ]
