# Generated by Django 5.2.5 on 2025-08-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0057_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="HRGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("target_interns_placed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("year",)},
            },
        ),
    ]
