# Generated by Django 6.0.4 on 2026-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_job_employment_type_job_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employment_type',
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
