"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# -------------------------------------------------------
# BASE CONFIG
# -------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure--oss785zp5ru6rw+7k!_@^pxx7wh7aert)0hw_#ayfemn@@$_!"
DEBUG = True
ALLOWED_HOSTS = ["*"]
X_FRAME_OPTIONS = "SAMEORIGIN"

# -------------------------------------------------------
# INSTALLED APPS
# -------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "pwa",
    "web",
    "administration",
    "authentication",
    "intern",
    "hostCampany",
    "payments",
    "storages",
    "hr",
    "coordination",
    "marketing",
    "widget_tweaks",
]

# -------------------------------------------------------
# MIDDLEWARE
# -------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "authentication.middleware.block_inactive_staff.BlockInactiveStaffMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

# -------------------------------------------------------
# CORS CONFIGURATION
# -------------------------------------------------------
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# -------------------------------------------------------
# TEMPLATES
# -------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# -------------------------------------------------------
# DATABASE (LOCAL DEVELOPMENT)
# -------------------------------------------------------

# Commented out PRODUCTION database (Do NOT use locally)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'dcgu2976726r9v',
#         'USER': 'ubad671tgplaes',
#         'PASSWORD': 'pdd280529eb41de7151adc38a73fc32267da0cec6a81cd545cc20073953c05eaf',
#         'HOST': 'c11ai4tgvdcf54.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com',
#         'PORT': '5432',
#     }
# }

# ✅ Use SQLite for local testing (safe and offline)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}





# -------------------------------------------------------
# PASSWORD VALIDATION
# -------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------------
# INTERNATIONALIZATION
# -------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Johannesburg"
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------
# STATIC & MEDIA FILES
# -------------------------------------------------------

# ✅ Your static files live here: C:\Users\user\internshipSuccess\web\static\web\assets
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# Tell Django where to find your static files
STATICFILES_DIRS = [
    BASE_DIR / "web" / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "media"

# -------------------------------------------------------
# AUTH
# -------------------------------------------------------
AUTH_USER_MODEL = "authentication.User"

# -------------------------------------------------------
# CSRF
# -------------------------------------------------------
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://www.internshipsuccess.co.za",
    "https://internshipsuccess-89ee09a75af7.herokuapp.com",
    "https://internshipsuccess-bkt-v1.s3.us-east-2.amazonaws.com",
]

# -------------------------------------------------------
# PWA CONFIG
# -------------------------------------------------------
PWA_APP_NAME = "Internship Success Admin"
PWA_APP_DESCRIPTION = "Admin site"
PWA_APP_THEME_COLOR = "#000000"
PWA_APP_BACKGROUND_COLOR = "#ffffff"
PWA_APP_DISPLAY = "standalone"
PWA_APP_SCOPE = "/"
PWA_APP_ORIENTATION = "any"
PWA_APP_START_URL = "/"
PWA_APP_STATUS_BAR_COLOR = "default"
PWA_APP_ICONS = [{"src": "static/images/icon-160x160.png", "sizes": "160x160"}]
PWA_APP_ICONS_APPLE = [{"src": "static/images/apple-icon-180x180.png", "sizes": "180x180"}]
PWA_APP_SPLASH_SCREEN = [
    {"src": "static/images/splash.png", "sizes": "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)"}
]
PWA_APP_DIR = "ltr"
PWA_APP_LANG = "en-US"

# -------------------------------------------------------
# EMAIL
# -------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "internshipsuccess1@gmail.com"
EMAIL_HOST_PASSWORD = "jwexuzxmxeqpgbyi"

# -------------------------------------------------------
# LOCAL FILE STORAGE (for development)
# -------------------------------------------------------

# Commented out AWS S3 for local development
# AWS_ACCESS_KEY_ID = os.getenv("AWS_S3_IAM_ACCESS_KEY")
# AWS_SECRET_ACCESS_KEY = os.getenv("AWS_S3_IAM_SECRETE_ACCESS_KEY")
# AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_S3_BUCKET_NAME")
# AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
# AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
# AWS_DEFAULT_ACL = None
# AWS_LOCATION = 'static'

# Use local file system storage
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'









