# Generated by Django 6.0.4 on 2026-05-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BunnyChow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
    ]
