# Generated by Django 6.0.4 on 2026-05-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BunnyChow', '0002_remove_department_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='resign_date',
        ),
    ]
