# Generated by Django 5.0.4 on 2025-07-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_type', models.CharField(choices=[('FUEL', 'Fuel'), ('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('RENT', 'Rent'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
