# Generated by Django 4.0.8 on 2024-05-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('hostCampany', '0002_alter_hostcomapany_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcomapany',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_comapanies', to='authentication.hostemployer'),
        ),
    ]
