# Generated by Django 5.0.2 on 2024-05-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostCampany', '0004_alter_workitem_logbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcomapany',
            name='joined_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
