# Generated by Django 5.0.2 on 2024-06-04 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('hostCampany', '0006_hostcomapany_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_logbooks', to='authentication.intern'),
        ),
    ]
