# Generated by Django 5.0.2 on 2024-06-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('hostCampany', '0007_logbook_intern'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverables',
            name='intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_deliverables', to='authentication.intern'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_workitems', to='authentication.intern'),
        ),
        migrations.AlterField(
            model_name='logbookassignment',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_logbook_assignments', to='authentication.intern'),
        ),
    ]
