# Generated by Django 5.1.1 on 2024-11-18 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hostCampany", "0009_report"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="timestamp",
            new_name="date",
        ),
    ]
