# Generated by Django 5.1.1 on 2025-06-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_user_profile_picture"),
        ("hostCampany", "0012_remove_logbook_company_remove_logbook_intern_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualification", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotations",
                        to="hostCampany.department",
                    ),
                ),
                (
                    "intern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotations",
                        to="authentication.intern",
                    ),
                ),
            ],
        ),
    ]
