# Generated by Django 5.1.1 on 2025-07-17 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0056_alter_intershipenrollment_status"),
        ("hostCampany", "0014_alter_rotation_intern"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="administration.intershipenrollment",
                    ),
                ),
                (
                    "host_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostCampany.hostcomapany",
                    ),
                ),
            ],
        ),
    ]
