# Generated by Django 5.1.1 on 2025-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostCampany", "0019_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostcomapany",
            name="contant_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
