# Generated by Django 5.2.5 on 2025-09-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostCampany", "0020_hostcomapany_contant_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostcomapany",
            name="company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIVATE", "Private"),
                    ("PRIVATE_WITH_IS", "Private With Internship Success"),
                    ("GOVERNMENT", "Government"),
                ],
                default="PRIVATE",
                max_length=50,
                null=True,
            ),
        ),
    ]
