# Generated by Django 5.2.5 on 2025-10-09 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0058_hrgoal"),
        ("authentication", "0003_user_profile_picture"),
        ("hostCampany", "0021_hostcomapany_company_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rotation",
            options={"ordering": ["start_date"]},
        ),
        migrations.RemoveField(
            model_name="rotation",
            name="qualification",
        ),
        migrations.AddField(
            model_name="rotation",
            name="deliverables",
            field=models.ManyToManyField(
                blank=True, to="administration.interndeliverable"
            ),
        ),
        migrations.AddField(
            model_name="rotation",
            name="work_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rotations",
                to="administration.workitem",
            ),
        ),
        migrations.AlterField(
            model_name="rotation",
            name="intern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rotations",
                to="authentication.intern",
            ),
        ),
    ]
