# Generated by Django 5.2.5 on 2025-10-10 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "hostCampany",
            "0022_alter_rotation_options_remove_rotation_qualification_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rotation",
            options={},
        ),
    ]
