# Generated by Django 5.1.1 on 2025-06-02 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hostCampany", "0014_alter_rotation_intern"),
        ("hr", "0010_scoringcategory_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlySiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("mentor_name", models.CharField(max_length=255)),
                ("mentor_email", models.EmailField(max_length=254)),
                ("supervisor_name", models.CharField(max_length=255)),
                ("supervisor_email", models.EmailField(max_length=254)),
                ("number_of_interns", models.IntegerField(default=0)),
                ("attendance_leave_recorded", models.TextField(blank=True, null=True)),
                ("invoice_update", models.TextField(blank=True, null=True)),
                ("accounting_officer", models.TextField(blank=True, null=True)),
                ("site_visits_conducted", models.IntegerField(default=0)),
                ("cases_reported", models.TextField(blank=True, null=True)),
                ("comments_mentor", models.TextField(blank=True, null=True)),
                ("comments_supervisor", models.TextField(blank=True, null=True)),
                ("comments_intern", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostCampany.hostcomapany",
                    ),
                ),
                (
                    "is_official",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_visits",
                        to="hr.staff",
                    ),
                ),
            ],
        ),
    ]
