# Generated by Django 5.1.1 on 2025-06-02 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0056_alter_intershipenrollment_status"),
        ("coordination", "0001_initial"),
        ("hostCampany", "0014_alter_rotation_intern"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date_reported", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                        ],
                        default="Open",
                        max_length=50,
                    ),
                ),
                ("response", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="hostCampany.hostcomapany",
                    ),
                ),
                (
                    "intern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="administration.intershipenrollment",
                    ),
                ),
            ],
        ),
    ]
