# Generated by Django 6.0.4 on 2026-05-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR Manager'), ('EMPLOYEE', 'Employee'), ('APPLICANT', 'Applicant')], default='APPLICANT', max_length=20),
        ),
    ]
